---
name: ci

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    uses: bendwyer/github-workflows/.github/workflows/flux-mirror-sync.yml@main
    with:
      mirror_version: v0.8.0
      dry_run: true
    secrets:
      ghcr_token: ${{ secrets.GITHUB_TOKEN }}

  check:
    if: always()
    needs:
      - validate
    uses: bendwyer/github-workflows/.github/workflows/github-check.yml@main
    with:
      jobs: ${{ toJSON(needs) }}
